"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

APP = ['cluster_switcher.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'app_icon.icns',
    'packages': ['PIL', 'pystray', 'urllib'],
    'includes': ['pystray', 'urllib.request', 'urllib.error'],
}

setup(
    name="Tanks Blitz Cluster Switcher",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
